services:
  db:
    image: postgres:13.9
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  redis:
    image: 'redis:6.2.1-alpine'
    command: redis-server
    ports:
      - 6379:6379/tcp
    volumes:
      - ../data/redis:/data
  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    stdin_open: true
    tty: true
    entrypoint: ./docker-entrypoint.sh
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000/tcp
    depends_on:
      - db
      - redis
volumes:
  postgres-data:
